import calendar from "/front/features/calendar.js"
import choose from "/front/features/suggestMeals.js"
import menu from "/front/utils/flipMenu.js"
import ruckus from "/front/features/ruckus.js"
import drawReminders from "/front/utils/drawReminders.js"